# Generated by Django 2.0.1 on 2018-02-04 14:51

import Create_Character.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime_created', models.DateTimeField(auto_now_add=True)),
                ('dateTime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=125)),
                ('job', models.CharField(max_length=125)),
                ('highestEducationLeval', models.CharField(max_length=125)),
                ('era', models.CharField(max_length=125)),
                ('gender', models.CharField(max_length=125)),
                ('age', models.PositiveSmallIntegerField()),
                ('location_born', models.CharField(max_length=125)),
                ('location_live', models.CharField(max_length=125)),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('constitution', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('dexterity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('appearance', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('power', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('intelligence', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('size', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('education', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('luck', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('appearanceDescription', models.TextField()),
                ('story', models.TextField()),
                ('healthPoint', models.PositiveSmallIntegerField(validators=[Create_Character.models.ValidateHealthPoint])),
                ('magicPoint', models.PositiveSmallIntegerField(validators=[Create_Character.models.ValidateMagicPoint])),
                ('sanity', models.PositiveSmallIntegerField()),
                ('build', models.SmallIntegerField()),
                ('damageBreak', models.PositiveSmallIntegerField()),
                ('mobility', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
