# Generated by Django 2.0.1 on 2018-02-11 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('relatedProperties', models.CharField(max_length=125)),
                ('relatedSkills', models.CharField(max_length=125)),
                ('reputation', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('initialValue', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('normalSuccessLevel', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('hardSuccessLevel', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('extremeSuccessLevel', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('relatedSkill', models.CharField(max_length=125)),
                ('damage', models.CharField(max_length=125)),
                ('range', models.CharField(max_length=125)),
                ('isPiercingInjury', models.BooleanField()),
                ('consecutiveLimit', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('load', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('firmness', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('presentEra', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Create_Character.WeaponCategory'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Create_Character.SkillCategory'),
        ),
    ]
